'use strict';

// Builds the redacted fixture from the owner's raw logs.
//
// DERIVED, NEVER TYPED. The fixture is regenerated by running this script; no
// line in it is hand-copied, so it cannot drift from the source.
//
// REDACTION RULE, and it is not negotiable: a private line is DROPPED WHOLE.
// It is never rewritten, never anonymised, never partially masked. A rewritten
// line still parses into a fake event, and a fixture that contains a fake
// event is worse than one that contains a gap. Every drop is counted and the
// count is written into the fixture header, so the gaps are visible.
//
//   node analysis/make-fixture.js
//
// Raw logs are gitignored and never leave the machine. Only the output of this
// script is committed.

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const LOG_DIR = 'C:\\Users\\Lindsey\\Desktop\\EQL Source\\eql-source\\state\\logs';
const OUT = path.join(__dirname, '..', 'sources', 'raw', '2026-08-10-weekly-task-fixture.log');

// Anything carrying player speech is dropped whole. Deliberately broad: a
// false drop costs a line, a false keep costs someone's private conversation.
const PRIVATE = [
  ' tells ', ' told ', ' says ', ' shouts ', ' auctions ',
  'You tell ', 'You told ', 'You say ', 'You shout ', 'You auction ',
  'tells you', 'You tell your', 'has gone Linkdead', ' is ONLINE', ' is OFFLINE',
];

// The windows to extract, chosen because together they carry every line shape
// the parser models plus both sides of a reset bracket.
const WINDOWS = [
  { file: 'eqlog_Avenrae_rivervale.txt',            from: 'Mon Aug 10 17:14:30', to: 'Mon Aug 10 17:28:20', note: 'Nagafen: invite, task assigned, instanced zone-in, kill, task updated, token' },
  { file: 'eqlog_Avenrae_rivervale.txt',            from: 'Mon Aug 10 17:48:15', to: 'Mon Aug 10 17:56:15', note: 'Lady Vox, same week — third of three tasks, reaching the 3/week cap' },
  { file: 'eqlog_Avenrae_rivervale_2026-08-15.txt', from: 'Tue Aug 11 20:40:35', to: 'Tue Aug 11 20:52:45', note: 'Lady Vox RE-ASSIGNED the next day — the far side of the reset bracket' },
  { file: 'eqlog_Avenrae_rivervale.txt',            from: 'Mon Aug 10 18:05:14', to: 'Mon Aug 10 18:05:22', note: 'REFUSED — identical exchange, no task line. Silence is the lockout signal.' },
  { file: 'eqlog_Avenrae_rivervale.txt',            from: 'Mon Aug 10 18:34:48', to: 'Mon Aug 10 18:34:58', note: 'Last REFUSED of 10 Aug — the lower bound of the reset bracket' },
];

const MONTHS = { Jan: 1, Feb: 2, Mar: 3, Apr: 4, May: 5, Jun: 6, Jul: 7, Aug: 8, Sep: 9, Oct: 10, Nov: 11, Dec: 12 };
const TS = /^\[([A-Za-z]{3}) ([A-Za-z]{3}) {1,2}(\d{1,2}) (\d{2}):(\d{2}):(\d{2}) (\d{4})\]/;

function stampKey(line) {
  const m = TS.exec(line);
  if (!m) return null;
  return Date.UTC(+m[7], MONTHS[m[2]] - 1, +m[3], +m[4], +m[5], +m[6]);
}
// WIDENED 31 Aug to match `TS_RE` in the engine: ` {1,2}(\d{1,2})` for the day.
//
// Session E found its own timestamp regex used a fixed `(\d{2})` for
// day-of-month, which would silently drop every line on days 1-9 if the client
// ever space-padded them the way `ctime()` does. `src/lockoutCore.js:212` was
// already tolerant; THIS function was the one place in my repo that was not.
//
// C then measured it and REFUTED the hazard for our corpus: 1,270,007 lines
// carry a single-digit day and every one is ZERO-padded — `strftime %d`, not
// `ctime()`. C also stated its own limit unprompted, that days 01-03 do not
// occur in its 16 files, so 4-9 is measured and 1-3 inferred.
//
// Widened anyway, on C's own recommendation: the cost is one character and the
// failure it prevents is silent. A tolerant pattern accepts everything the
// strict one did.
function boundKey(s) {
  const m = /^([A-Za-z]{3}) ([A-Za-z]{3}) {1,2}(\d{1,2}) (\d{2}):(\d{2}):(\d{2})$/.exec(s);
  return Date.UTC(2026, MONTHS[m[2]] - 1, +m[3], +m[4], +m[5], +m[6]);
}
function isPrivate(line) {
  return PRIVATE.some((p) => line.includes(p));
}

// A fixture is evidence, not a transcript. Only the shapes the parser models
// are kept, plus named-mob kill lines so the kill is visible beside the task
// it completes. Everything else is dropped WHOLE and counted — same treatment
// as a redaction, so the gaps stay visible.
//
// A named mob is one whose kill line does not begin with an article; trash is
// "A fire giant warrior has been slain", a name is "Lord Nagafen has been slain".
const KEEP = [
  /^\[[^\]]+\] You have been assigned the task '/,
  /^\[[^\]]+\] Your task '.+' has been updated\.$/,
  /^\[[^\]]+\] You have been given: /,
  /^\[[^\]]+\] You have entered .+\.$/,
  /^\[[^\]]+\] .+ has asked you to join the instance: /,
  /^\[[^\]]+\] .+ has accepted your offer to join your expedition\.$/,
  /^\[[^\]]+\] You are not the expedition leader, /,
  /^\[[^\]]+\] .+ has been removed from .+\.$/,
  /^\[[^\]]+\] (?![AaTt]n? |The )[A-Z][^ ]* .*has been slain by /,
  // The Voidling exchange — the lockout signal itself. `You say` lines are the
  // player's own keyword input to an NPC dialogue tree, not conversation, so
  // they are evidence rather than private chat. Only the two keywords are kept.
  /^\[[^\]]+\] You say, '(Hail, voidling|danger)'$/,
  /^\[[^\]]+\] Voidling says, '/,
];
const isKept = (line) => KEEP.some((re) => re.test(line));

async function extract(win) {
  const kept = [];
  let redacted = 0;
  let combat = 0;
  const lo = boundKey(win.from);
  const hi = boundKey(win.to);
  const rl = readline.createInterface({
    input: fs.createReadStream(path.join(LOG_DIR, win.file), { encoding: 'utf8' }),
    crlfDelay: Infinity,
  });
  for await (const line of rl) {
    const k = stampKey(line);
    if (k === null || k < lo) continue;
    if (k > hi) { rl.close(); break; }
    // Keep-check runs FIRST for the Voidling keywords: `You say, 'danger'` is
    // caught by the broad `You say ` privacy rule, and it is the single most
    // important line in this fixture. Everything else still goes through the
    // privacy filter before anything else.
    const voidlingKeyword = /^\[[^\]]+\] You say, '(Hail, voidling|danger)'$/.test(line);
    if (!voidlingKeyword && isPrivate(line)) { redacted++; continue; }
    if (!isKept(line)) { combat++; continue; }
    kept.push(line);
  }
  return { kept, redacted, combat };
}

(async () => {
  const parts = [];
  let totalRedacted = 0;
  let totalCombat = 0;

  for (const win of WINDOWS) {
    const { kept, redacted, combat } = await extract(win);
    totalRedacted += redacted;
    totalCombat += combat;
    parts.push(
      `# --- ${win.note}`,
      `# --- source: ${win.file}  window: [${win.from}] .. [${win.to}]`,
      `# --- ${redacted} private line(s) dropped whole, ${combat} unmodelled line(s) dropped whole`,
      ...kept,
      ''
    );
  }

  const header = [
    '# EQLS Lockouts — redacted fixture, built by analysis/make-fixture.js',
    '#',
    '# Verbatim excerpts from the owner\'s own EverQuest Legends logs. Every line',
    '# below is exactly as the client wrote it. Nothing has been rewritten: lines',
    '# carrying private conversation were DROPPED WHOLE, because a rewritten line',
    '# still parses into a fake event.',
    '#',
    `# Character: Avenrae, server rivervale. Dropped: ${totalRedacted} private, ${totalCombat} unmodelled.`,
    '#',
    '# CLOCK: stamps are the game client\'s local wall clock and carry no timezone.',
    '# The machine that wrote them is set to "Eastern Standard Time"',
    '# (Windows tz id; UTC-05:00 base, DST active in August, so UTC-04:00 for',
    '# these lines). Read off the OS on 21 Aug 2026, not asked for and not guessed.',
    '# Recorded here because every published candidate reset rule is stated in',
    '# Pacific, and without this the comparison is off by an unknown constant.',
    '#',
    '# ENCODING: measured, not assumed. Across all 15 logs, exactly 9 bytes are',
    '# >= 0x80, and all 9 are EF BF BD (U+FFFD). Valid UTF-8. Read as UTF-8.',
    '# The corpus byte total is NOT quoted here: an earlier revision typed',
    '# 440,214,858 into this generated artifact and the measured sum is',
    '# 433,914,867. A figure typed into a file whose whole point is that it is',
    '# generated is the fault this project exists to catch. See analysis/findings.json.',
    '#',
    '# LINE ENDINGS: the source logs are CRLF. This fixture is written LF and',
    '# .gitattributes keeps it that way; the parser strips a trailing CR either way.',
    '#',
    '# Lines beginning with # are this header and are not log content.',
    '',
  ];

  fs.writeFileSync(OUT, header.concat(parts).join('\n'), 'utf8');
  const lines = header.concat(parts).length;
  process.stdout.write(`wrote ${OUT}\n${lines} lines, ${totalRedacted} private dropped, ${totalCombat} combat dropped\n`);
})();
